server:
  port: 8083
spring:
  application:
    name: search-service
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.25.131:9300  # 配置ES 连接
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 10  # 每10秒拉取一次服务
  instance:
    lease-expiration-duration-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-renewal-interval-in-seconds: 10 # 10秒不发送就过期