server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:     # 配置连接sql
    url: jdbc:mysql:///db_lian
    username: root
    password: root
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 配置服务心跳时间
    lease-expiration-duration-in-seconds: 15 # 心跳过期时间
mybatis:
  type-aliases-package: com.leyou.item.pojo   # mybatis 包扫描
