server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:     # 配置连接sql
    url: jdbc:mysql:///leyou_86
    username: root
    password: root
  rabbitmq:
    host: 192.168.25.131
    username: leyou    # 设置mq的用户
    password: leyou
    virtual-host: /leyou
    template:
      exchange: LEYOU.ITEM.EXCHANGE   # 设置交换机
    publisher-confirms: true    # 生产者确认机制，确保消息会正确发送
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 10  # 每10秒拉取一次服务
  instance:
    lease-renewal-interval-in-seconds: 5 # 配置服务心跳时间
    lease-expiration-duration-in-seconds: 15 # 心跳过期时间
mybatis:
  type-aliases-package: com.leyou.item.pojo   # mybatis 包扫描
