server:
  port: 8086
spring:
  application:
    name: sms-service
  redis:
    host: 192.168.26.131
  rabbitmq:
    host: 192.168.25.131
    username: leyou
    password: leyou
    virtual-host: /leyou
leyou:
  sms:
    accessKeyId: LTAIeNbZLyyeTnAn # 你自己的accessKeyId
    accessKeySecret: p8SiyJaBEDAyU92ZPRDNIMCLo71YwC # 你自己的AccessKeySecret
    signName: 乐优商城 # 签名名称
    verifyCodeTemplate: SMS_133976814 # 模板名称